### ISSUE TITLE
BC template property

### ISSUE THREAD

**Issue by andrewblake1** [kartik-v/yii2-detail-view#50]
Just updated and discovered the BC re template property. Perhaps you have good reason to do it but thought I would mention that it breaks my use as described in my discus comment where I used
divs instead of table to get around some issues.

Of course I can override your init method so no major, but thought I would mention my use case as chances are that others are bound to strike issues with tables as well, and for me personally it was better before. With the template property not usable I think the widget looses a tiny bit of flexibility - still brilliant though.

**Comment by kartik-v** [comment]
Many of the newer functionalities in the detail view will be broken if you use yii's default template method

- creating detail view merged row sections will not be possible
- automatically hiding certain rows for edit mode and view mode will not be possible
- styling each table row will not be possible
- and a few other enhancements

**Comment by kartik-v** [comment]
Many of the newer functionalities in the detail view will be broken if you use yii's default template method

- creating detail view merged row sections will not be possible
- automatically and selectively hiding certain rows for edit mode and view mode will not be possible
- styling each table row will not be possible
- and a few other enhancements

However in the newer update, one can use `rowOptions`, `labelColOptions`, `valueColOptions` at the widget level or widget `attributes` level to configure advanced layout functions. It will require you to use a table layout.

**Comment by kartik-v** [comment]
Many of the newer functionalities in the detail view will be broken if you use yii's default template method

- creating detail view merged row sections will not be possible
- automatically and selectively hiding certain rows for edit mode and view mode will not be possible
- corollary of the above -- you can entirely show different rows to display for view mode and different rows for editing in edit mode
- styling each table row will not be possible
- and a few other enhancements

However in the newer update, one can use `rowOptions`, `labelColOptions`, `valueColOptions` at the widget level or widget `attributes` level to configure advanced layout functions. It will require you to use a table layout.

**Comment by andrewblake1** [comment]
Table layout has display problem with select2 widget and overflow property. I described in disqus - noticeable for me in modal because of narrow window width. Its been a while but I seem to remember trying everything I could with css and spending a fair amount of time to try and get it to work sensibly before utilising the the template property to get around it - not saying that it can't be done in table - I just couldn't figure it out.

I assumed you probably had a logical reason for the BC, but thought worth raising here as likely that others may hit issues with table layout and thought perhaps there might be another way you could achieve your goals with the issue described in mind. I prefer not to extend unless I have to.

Using Chromes developer tools an example of the select2 widget display problem in a table can be witnessed in your detailview demo in edit mode by altering the selection of the text in the select2 widget such that it would extend beyond the right bound of the form (not just the the bound of the widget to cause the ellipses but further past form edge). You will see synopsis and bookname widgets pushed out and the form then becomes horizontally scrollable - probably not desirable for most and not what would be expected. Though text this long isn't practical of course in a normal window for a select item, it does become a problem on mobile devices - or in my case in modal.

I suspect that as more people use your detail view in edit mode on mobile devices with select2 then I think others will eventually notice this.

**Comment by kartik-v** [comment]
With the latest updates... I cannot replicate your situations.

So in summary:
-  the table layout seems to work fine, the inputs are responsive and works across sizes/resolutions
-  you can test the main demo [on the demo page](http://demos.krajee.com/detail-view-demo) and scale the sizes of the window to test
-  you can test the [modal demo in the usage section on the docs page](http://demos.krajee.com/detail-view#usage) and check the detail view working inside a modal.

**Comment by andrewblake1** [comment]
Am trying to re-test but your demo page is currently return server error #64

**Comment by kartik-v** [comment]
you may recheck now...

**Comment by andrewblake1** [comment]
still getting server error

**Comment by andrewblake1** [comment]
in chrome for your demo in edit/update mode, set the value of the text for the author to:

<span class="select2-chosen" id="select2-chosen-1">F. Scott Fitzgerald asdf asdfjkh aksjfh aksjdfhak akshdfk aklsdfh alskjdfh lkasjhdf lkasjdhf alksjdhfkasdh askjdfh askjdfh alksjdfh askdjfh aslkdfh aksd asdf asdflkj as;dflkj as;ldfkj as;dlkf asd;fj a;sdkflj dsa;fklj f </span>

You may have to narrow your browser window a bit to see the issue. In mine, the textarea box for synopsis (for example) has now grown beyond the right edge of the form (though hidden), but the form is now horizontally scrollable.

That is an example of the type of thing going wrong with select2 inside table. I tried for quite some time to try and get it to work in tables - not saying it can’t be done - just saying I couldn’t do it.

**Comment by kartik-v** [comment]
The table rendering, Select2 within table, responsiveness, display inside a model, autosizing all work well.

Your use case is something which is very specific to your individual application design and need. Its not something which everyone may design or use.

You are trying to do quite a few things by restricting the design very specific to a situation which is not universal. For example you are trying to display a very long text - within one LINE... within a SELECT2 and all of these constrained within a modal or a mobile display view.

IMO... its recommeneded to design such deviations in each app - because its not the DetailView or SELECT2 redesign which may help such cases - but the way you are able to trap such data and redesign for your user need.

If you for a moment forget about the Detail

**Comment by kartik-v** [comment]
The table rendering, Select2 within table, responsiveness, display inside a model, autosizing all work well.

Your use case is something which is very specific to your individual application design and need. Its not something which everyone may design or need or use. 

You are trying to do quite a few things by restricting the design very specific to a situation which is not universal. For example you are trying to display a very long text - within one LINE... within a SELECT2 and all of these constrained within a modal or a mobile display view. 

IMO... its recommeneded to design such deviations in each app - because its not the DetailView or SELECT2 redesign which may help such cases - but the way you are able to trap such data and redesign for your user need.

For example, even if you have an ability to magically display all the overflowing content in the DetailView... IMO.. the choice of input selections from app design is still important. A checkbox or dropdown is normally not designed from a user experience perspective to have its text flowing into multiple lines. You would need to control the display by abbreviating / truncating - OR use for example the HTML formatted method of displaying Select2 records.

**Comment by kartik-v** [comment]
The table rendering, Select2 within table, responsiveness, display inside a model, autosizing all work well.

Your use case is something which is very specific to your individual application design and need. Its not something which everyone may design or need or use. 

You are trying to do quite a few things by restricting the design very specific to a situation which is not universal. For example you are trying to display a very long text - within one LINE... within a SELECT2 and all of these constrained within a modal or a mobile display view. 

IMO... its recommended to design such deviations separately in each app - because its not the DetailView or SELECT2 redesign which may help such cases - but the way you are able to trap such data and redesign for your user need.

For example, even if you have an ability to magically display all the overflowing content in the DetailView... IMO.. selecting the right choice of input from an app design perspective is still important. A checkbox or dropdown is normally not designed from a user experience perspective to have its text flowing into multiple lines. You would need to control the display by abbreviating / truncating - OR use for example the HTML formatted method of displaying Select2 records.

**Comment by andrewblake1** [comment]
Ok, fair enough. FYI I have many examples of this occurring in my app, the first is just selecting a contact where I use full name and email - as there are many people that share the same name appending email helps uniquely identify. Everyone wants their software to work on mobiles smoothly, and I use modals for inserting new records in grid views. IMHO these uses aren’t too extreme however you are right, it will be rare that developers do this - though I suspect it will probably happen again.

When I had tried to fix in tables before using divs All I had wanted is for ellipses or truncation to occur - you can see that does happen but with weird side effects. Not sure yet what you mean by HTML formatted method of displaying Select2 records - will have a look later - perhaps there is a solution there. If I could find anyway of truncating that data without weird side effects on the client without using divs - I would. Truncating on the server is a bit too ugly of a solution for me.

My main reasons for raising as an issue as opposed to just extending is that I have experienced many limitations when using tables in the past that divs got me past. I suspect that the DetailView of yii2 has the template property to allow people to deal with such things. I don’t think tables will cater to all scenarios - certainly good for most though.

I can resolve in one of 2 ways. I can extend, or can resolve and create a PR if you are willing? If I extend then I potentially miss any other goodies you add in the future unless I regularly check after composer updates. If I resolve, the resolution would probably be something simple like checking if template property has been used or not but if used wouldn’t make use of your new functionality where colspan is involved etc. If used would probably not have your newer functionality.

**Comment by kartik-v** [comment]
You are always welcome to add a PR.

Just to note... that the `DetailView` and `GridView` are designed by default to be tables.

The newer functionality of merging columns hiding and inserting rows are plain tabular layout edits. If you do have a suggestion to extend these let know.

Again IMO... if you need non tabular layouts and advanced positioning - then using a DetailView to render the complex layout is actually not the best way IMO... Rather using a normal view rendered using something like `\kartik\builder\Form` widget is better. This `\kartik\builder\Form` has configuration very similar to the DetailView - but offers much more advanced layout configuration (non-tabular) and supports the various bootstrap form layouts. Its just that you do not have a toggle mode inbuilt between view and edit... however you can do that in one go by setting the `staticOnly` property to `true` at the form level.

**Comment by kartik-v** [comment]
On using HTML formatted content for each row in Select2... you can see the templating example in the [Select2 widget usage section](http://demos.krajee.com/widget-details/select2#usage) - which shows a list of flag icons beside each State.

You can extend the concept to render your own html content with relevant CSS, Font sizes, or new lines for each row. 

Also check this on the [templating section on the plugin site](http://select2.github.io/select2/).

**Comment by andrewblake1** [comment]
Apols for reopening - just wanted to let you know havn't done PR or tried to fix as found a recent css fix to Select2 resolves the issue I was having - hence I can use the default table layout. Thought I would mention as I saw a Disqus comment this morning asking about select2 v4. For me was easy 3 lines in site.css but thought best mention as v4 already has that fix I think.
